import type { Rng, Weighted } from '../rng'
import type { StatKey, StatMod, StatModMode } from '../combat/stats'
import { STAT_KEYS, STAT_SCALE } from '../combat/stats'

/**
 * Item generation: realize a concrete item instance from a base template and
 * an affix pool.
 *
 * A pure function with no ECS involvement, in the same spirit as
 * `computeDamage` and `computeStats`: every drop in the game routes through
 * here eventually, so it lives in isolation where it can be reasoned about,
 * tested, and tuned without touching an entity.
 *
 * The affix-count-per-rarity rule and prefix/suffix caps are recorded in
 * docs/decisions/0014; selection weighting and value granularity in
 * docs/decisions/0015.
 *
 * Input shapes mirror the content schemas (`ItemBase`, `Affix`,
 * `StatModRange`). Core cannot import content (the dependency points the
 * other way), so these are duplicated by design; the content schema is the
 * follower if they diverge. Slot and affix ids are opaque strings here — the
 * roller only ever compares them for equality, so core does not need to know
 * the slot vocabulary.
 */

/** Whether an affix occupies a prefix or a suffix slot on the item. */
export type AffixKind = 'prefix' | 'suffix'

/**
 * The rarities this roller can produce. A deliberate subset of the content
 * schema's `RARITIES`: legendary and unique items are not generated by affix
 * rolling and are out of scope here.
 */
export type LootRarity = 'common' | 'magic' | 'rare'

/**
 * A stat modifier that rolls within a range at generation time. Mirrors the
 * content schema's `StatModRange`.
 */
export interface StatModRange {
  stat: StatKey
  mode: StatModMode
  min: number
  max: number
}

/** One tier of an affix. Mirrors the content schema's `Affix` tier entries. */
export interface LootAffixTier {
  /** 1 is the strongest tier. */
  tier: number
  /** Minimum item level for this tier to be reachable. */
  itemLevel: number
  weight: number
  mods: readonly StatModRange[]
}

/** An affix as the roller sees it. Mirrors the content schema's `Affix`. */
export interface LootAffix {
  id: string
  kind: AffixKind
  /** Which equipment slots this affix can appear on. */
  slots: readonly string[]
  tiers: readonly LootAffixTier[]
}

/** A base item template. Mirrors the content schema's `ItemBase`. */
export interface LootItemBase {
  id: string
  slot: string
  /** Modifiers every instance of this base rolls, before affixes. */
  implicits: readonly StatModRange[]
}

/**
 * One affix as rolled onto an item. `affixId` + `tier` are the provenance:
 * together with the affix definition they identify exactly which ranges the
 * `mods` values were rolled from, for display and audit.
 */
export interface RolledAffix {
  affixId: string
  kind: AffixKind
  tier: number
  mods: StatMod[]
}

/**
 * A concrete item instance. Plain JSON-serializable data: strings, numbers,
 * and arrays only, so it survives the save/hash round trip untouched.
 * `affixes` is in roll order — display grouping is the client's concern.
 */
export interface RolledItem {
  baseId: string
  slot: string
  itemLevel: number
  rarity: LootRarity
  implicits: StatMod[]
  affixes: RolledAffix[]
}

/**
 * Affix budget per rarity — see docs/decisions/0014:
 *
 * - common: no affixes (implicits only).
 * - magic: 1–2 affixes, at most 1 prefix and 1 suffix.
 * - rare: 3–6 affixes, at most 3 prefixes and 3 suffixes.
 *
 * Exported so UI and content tooling can read the same rule instead of
 * re-encoding it.
 */
export const RARITY_AFFIX_RULES: Readonly<
  Record<LootRarity, { readonly minAffixes: number; readonly maxAffixes: number; readonly perKindCap: number }>
> = {
  common: { minAffixes: 0, maxAffixes: 0, perKindCap: 0 },
  magic: { minAffixes: 1, maxAffixes: 2, perKindCap: 1 },
  rare: { minAffixes: 3, maxAffixes: 6, perKindCap: 3 },
}

const STAT_KEY_SET: ReadonlySet<string> = new Set(STAT_KEYS)
const MOD_MODES: readonly StatModMode[] = ['flat', 'increased', 'more']

/**
 * Roll a concrete item from a base, an affix pool, an item level, and a
 * rarity.
 *
 * Pure and deterministic: the only source of variation is `rng`. The caller
 * must pass `eligibleAffixes` in a deterministic order (e.g. sorted by id) —
 * the pool's order is part of the inputs, and two different orderings of the
 * same pool are different inputs to the rng stream.
 *
 * Draw order is fixed and is part of the replay contract:
 *
 * 1. One draw per implicit, in `base.implicits` order — except degenerate
 *    ranges (`min === max`), which consume no draw.
 * 2. One draw for the affix count (magic/rare only; common draws nothing).
 *    Drawn before the pool is inspected, so a pool change never shifts it.
 * 3. Per affix: one draw to pick the affix (weighted by the sum of its
 *    eligible tiers' weights), one draw to pick the tier (weighted among
 *    eligible tiers), then one draw per mod in tier order (degenerate ranges
 *    again consume none).
 *
 * Eligibility: an affix must list the base's slot, must not already be on the
 * item, must not exceed its kind's cap (decision 0014), and must have at
 * least one tier whose `itemLevel` gate is ≤ the item's level (exactly-at-
 * gate is eligible). If the eligible pool runs dry before the rolled count is
 * reached, the item keeps its rarity and simply carries fewer affixes.
 *
 * Value granularity (decision 0015): integer-endpoint ranges roll a uniform
 * integer in [min, max]; fractional ranges roll a continuous uniform value
 * quantized to 1/{@link STAT_SCALE} and clamped into [min, max].
 *
 * Malformed inputs (non-finite ranges, min > max, unknown stat keys or modes,
 * a non-positive-integer item level, an unsupported rarity) throw immediately
 * with the field named — bad data entering the loot stream is exactly the
 * silent corruption the state-hash invariants exist to catch.
 */
export function rollItem(
  base: LootItemBase,
  eligibleAffixes: readonly LootAffix[],
  itemLevel: number,
  rarity: LootRarity,
  rng: Rng,
): RolledItem {
  if (!Number.isInteger(itemLevel) || itemLevel < 1) {
    throw new Error(`rollItem: itemLevel must be a positive integer, got ${itemLevel}`)
  }
  const rule = RARITY_AFFIX_RULES[rarity]
  if (!rule) {
    throw new Error(`rollItem: unsupported rarity "${String(rarity)}"`)
  }

  const implicits = base.implicits.map((range, i) =>
    rollMod(range, rng, `base "${base.id}" implicits[${i}]`),
  )

  const affixes: RolledAffix[] = []
  if (rule.maxAffixes > 0) {
    const count = rng.intInclusive(rule.minAffixes, rule.maxAffixes)
    const usedIds = new Set<string>()
    const kindCounts: Record<AffixKind, number> = { prefix: 0, suffix: 0 }

    for (let i = 0; i < count; i++) {
      const candidates: Weighted<{ affix: LootAffix; tiers: LootAffixTier[] }>[] = []
      for (const affix of eligibleAffixes) {
        if (usedIds.has(affix.id)) continue
        if (kindCounts[affix.kind] >= rule.perKindCap) continue
        if (!affix.slots.includes(base.slot)) continue
        const tiers = affix.tiers.filter((t) => t.itemLevel <= itemLevel && t.weight > 0)
        if (tiers.length === 0) continue
        let weight = 0
        for (const t of tiers) weight += t.weight
        candidates.push({ value: { affix, tiers }, weight })
      }
      if (candidates.length === 0) break

      const { affix, tiers } = rng.weighted(candidates)
      const tier = rng.weighted(tiers.map((t) => ({ value: t, weight: t.weight })))
      const mods = tier.mods.map((range, j) =>
        rollMod(range, rng, `affix "${affix.id}" tier ${tier.tier} mods[${j}]`),
      )
      affixes.push({ affixId: affix.id, kind: affix.kind, tier: tier.tier, mods })
      usedIds.add(affix.id)
      kindCounts[affix.kind] += 1
    }
  }

  return { baseId: base.id, slot: base.slot, itemLevel, rarity, implicits, affixes }
}

/**
 * Roll one mod value uniformly within its range — see the granularity rule in
 * decision 0015 and the draw-order contract on {@link rollItem}.
 */
function rollMod(range: StatModRange, rng: Rng, where: string): StatMod {
  const { stat, mode, min, max } = range
  if (!STAT_KEY_SET.has(stat)) {
    throw new Error(`rollItem: ${where} has unknown stat key "${String(stat)}"`)
  }
  if (!MOD_MODES.includes(mode)) {
    throw new Error(`rollItem: ${where} has unknown mode "${String(mode)}"`)
  }
  assertFinite(min, `${where}.min`)
  assertFinite(max, `${where}.max`)
  if (min > max) {
    throw new Error(`rollItem: ${where} has min ${min} > max ${max}`)
  }

  let value: number
  if (min === max) {
    // Degenerate range: nothing to roll, and — deliberately — no draw, so a
    // fixed-value mod never shifts the stream.
    value = min
  } else if (Number.isInteger(min) && Number.isInteger(max)) {
    value = rng.intInclusive(min, max)
  } else {
    // Continuous roll, quantized to the stat quantum (decision 0005) so item
    // values never carry hash-hostile float dust. Quantization can push a
    // value one quantum past an off-grid endpoint, hence the clamp.
    const raw = rng.float(min, max)
    const scaled = raw * STAT_SCALE
    value = Math.abs(scaled) >= Number.MAX_SAFE_INTEGER ? raw : Math.round(scaled) / STAT_SCALE
    value = Math.min(max, Math.max(min, value))
  }
  return { stat, mode, value }
}

function assertFinite(value: number, field: string): void {
  if (typeof value !== 'number' || !Number.isFinite(value)) {
    throw new Error(`rollItem: ${field} is ${value}; mod ranges must be finite numbers`)
  }
}
